### ISSUE TITLE
Where is the  chinese doc?

### ISSUE THREAD

**Issue by xiaomubiao** [iTimeTraveler/hexo-theme-hiero#1]
the  font  look  not good.

**Comment by iTimeTraveler** [comment]
@xiaomubiao 中文文档因为懒散，还没翻译过来=_=。不过对于字体你有什么好的建议么，你可以试着改改主题里的字体看看，然后直接给我Pull Request都行。我对字体这方面也是试了好几种，没找见比较和谐漂亮的所以就搁置了。。
