### ISSUE TITLE
多说要关了是不是意味着畅言要起来了

### ISSUE THREAD

**Issue by baylin87** [iTimeTraveler/hexo-theme-hiero#11]
大大把多说评论款融入了主题，很完美，可惜了。

**Comment by iTimeTraveler** [comment]
@baylin87 在国内的我们这点还是挺悲催的 :rofl:  我再观察对比一下网易云跟帖和畅言

**Comment by xiaomubiao** [comment]
畅言要备案号的，虽然我也看到过没备案的域名也在用，不过看条款是需要备案的

**Comment by Z4HD** [comment]
私以为畅言无用的功能过多且追踪回复没有网易方便。

**Comment by iTimeTraveler** [comment]
@Z4HD 就是网易云跟帖必须要自己的域名，github pages就没法用了。我闲了先加上网易云跟帖

**Comment by baylin87** [comment]
@iTimeTraveler 我在comment.ejs按你的格式在后面添加了一个elseif，插入了网易云跟帖通用代码（我有域名），然后hexo d上去就没显示了。。是不是还要改别的地方？

**Comment by iTimeTraveler** [comment]
@baylin87 网易云跟帖的配置比较复杂，测试的话建议你参考一下Next主题的说明： http://theme-next.iissnan.com/third-party-services.html#yungentie  我试过一次测试成功了，但是鉴于没有申请域名，就没有深入部署

**Comment by iTimeTraveler** [comment]
@baylin87 @Z4HD @xiaomubiao Hi，我刚把网易云跟帖评论功能添上了，你们有空了帮我试试哈，看看有没有bug

**Comment by baylin87** [comment]
@iTimeTraveler 刚测了下，添加了key，deploy上去没有显示==。

**Comment by Z4HD** [comment]
@iTimeTraveler 主题的友言评论可能已经失效，建议复查。

**Comment by iTimeTraveler** [comment]
@baylin87 我这边没有域名，所以没法评测。但是在本地测试是成功的，奇怪。。郁闷了

**Comment by iTimeTraveler** [comment]
@Z4HD 友言是不是被封了，我这边测试总显示502 Bad Gateway :rofl:
