### ISSUE TITLE
考虑将使用文档放置到GitHub wiki吗？

### ISSUE THREAD

**Issue by Z4HD** [iTimeTraveler/hexo-theme-hiero#16]
放在README.md里的话加点东西还要发个PR，略显麻烦。不似wiki可以随时进行编辑增删等等。

**Comment by iTimeTraveler** [comment]
@Z4HD 当然，不知道你方便么。我这边有时候时间不充裕，也有懒劲，就懈怠了 :rofl:

**Comment by Z4HD** [comment]
@iTimeTraveler 我就是来询问您喜不喜欢让操作文档放置在Github WIKI里，免得我自己瞎改给您造成麻烦。

**Comment by Z4HD** [comment]
@iTimeTraveler 这周末我就会找时间把您的README.md和README.zh.md的内容迁移到Github Wiki页面，麻烦神触到时候帮我检查与改正错误，若是造成麻烦还请神触多多包涵。

**Comment by Z4HD** [comment]
anyone并没有编辑权限，可能是您维持了默认设置？
***
如果您希望让任何人共同维护wiki页面，具体设置方法可以[参考此处](https://help.github.com/articles/changing-access-permissions-for-wikis/)。

**Comment by iTimeTraveler** [comment]
@Z4HD ok，麻烦你了。你再试试吧，我改了权限。
