### ISSUE TITLE
文章摘要可以限制字数吗？

### ISSUE THREAD

**Issue by YoungHuang** [iTimeTraveler/hexo-theme-hiero#17]
在文章中加入后，文章在列表里会折叠展示，但是显示的文章并不是上方的文章，好像是展示了固定大小的字数。

**Comment by iTimeTraveler** [comment]
@YoungHuang Hello, 这个issue里有讨论，你看看吧-> https://github.com/iTimeTraveler/hexo-theme-hiero/issues/10

**Comment by YoungHuang** [comment]
@iTimeTraveler 谢谢
