### ISSUE TITLE
关于首页针对特定文章不予显示的问题

### ISSUE THREAD

**Issue by myguybetter** [iTimeTraveler/hexo-theme-hiero#20]
自己有几篇文章不希望在首页显示，但是一直没有想到很好的办法隐藏
next主题有相关代码，但是自己借鉴后却因`post_template`值未定义导致无法实现

请问能指导一下么，谢谢！

**Comment by myguybetter** [comment]
没有dalao来指导一下么( •̥́ ˍ •̀ू )

**Comment by iTimeTraveler** [comment]
@myguybetter 有一种方法是把原始文章的markdown文件放到和 `_post` 文件夹同级目录下，新建一个 `_draft` 文件夹，放到这个文件夹里，就会当做草稿隐藏，干脆不予显示

就像这个： https://github.com/iTimeTraveler/iTimeTraveler.github.io/tree/site/source

**Comment by myguybetter** [comment]
@iTimeTraveler 但是我这个文章还是希望在分类目录中的相应目录下显示，如果放`_draft`里面的话就没有显示了，请问能有更好一点的办法吗？

**Comment by iTimeTraveler** [comment]
@myguybetter 目前的主题功能还没有这方面的逻辑，我有空了参考一下next主题试着实现一下，好了再跟你说一声
