### ISSUE TITLE
网易云跟帖并没有在文章中用？

### ISSUE THREAD

**Issue by w-nba** [iTimeTraveler/hexo-theme-hiero#23]
<% if (!index && post.comments && (theme.duoshuo_shortname || theme.disqus_shortname || theme.uyan_uid || theme.wumii || theme.livere_shortname)){ %>
        <%- partial('comment') %>
      <% } %>

**Comment by iTimeTraveler** [comment]
@w-nba 不是，post.comments 指的是每篇文章自己的Markdown头部设置有个 `comments: true` 字段，如果文章里显示不出来评论可能是这个字段为 `false` 或者没有。

```markdown
---
title: 【Android】app打包成apk文件以后，如何查看VersionCode、VersionName等版本信息
layout: post
date: 2015-12-25 10:57:55
comments: true
tags: [Android]
categories: [Android]
keywords: Android
description: 
---
```
