### ISSUE TITLE
关于页面的图片在哪里设置的？

### ISSUE THREAD

**Issue by MSK0379** [iTimeTraveler/hexo-theme-hiero#26]
我尝试了更改发现存在问题！

**Comment by iTimeTraveler** [comment]
@MSK0379 解决了么，你是想直接在代码中去掉关于页面的图片部分代码吗？

**Comment by MSK0379** [comment]
我直接把那段代码注释掉了，实现了去掉那个图片。

**Comment by MSK0379** [comment]
@iTimeTraveler 我是直接注释掉那段代码实现不显示那个图片。我想请教以下您是如何在首页中显示每篇文章的部分内容，点击之后显示所有内容的，我摸索了好久都没能解决，谢谢！

**Comment by Z4HD** [comment]
@MSK0379 
您是想要添加文章摘要吗？[这篇wiki文章](https://github.com/iTimeTraveler/hexo-theme-hiero/wiki/FAQ-（中文版）) 可能对您有帮助。

**Comment by MSK0379** [comment]
@Z4HD 好的  谢谢了0.0我先看看 有问题的话 请教您。膜拜.gif

**Comment by Z4HD** [comment]
@MSK0379 问题要是解决了记得及时关闭issue, 3Q2X

**Comment by MSK0379** [comment]
@Z4HD 好的谢谢
