### ISSUE TITLE
打扰了，想请教一下，怎么添加表格呢？

### ISSUE THREAD

**Issue by QingyangChen** [iTimeTraveler/hexo-theme-hiero#27]
我尝试用网上其他人的例子，但是做出来的只有文字，没有形成表格。
![image](https://user-images.githubusercontent.com/18388868/28457094-634b791c-6e37-11e7-8a32-f5ac6c5c3484.png)
![image](https://user-images.githubusercontent.com/18388868/28457103-6ea0559e-6e37-11e7-8ef3-3b62d44235c9.png)
谢谢

**Comment by iTimeTraveler** [comment]
Hello， @QingyangChen 可能是你的表格"|"后面少了空格的原因，你可以参考下这个教程[单元格和表头](http://xianbai.me/learn-md/article/extension/table.html) 。其中有句话，`为了使 Markdown 更清晰，| 和 - 两侧需要至少有一个空格（最左侧和最右侧的 | 外就不需要了）。`


像我下面这样：

|    name    | age |
| ---------- | --- |
| LearnShare |  12 |
| Mike       |  32 |

**Comment by QingyangChen** [comment]
嗯，谢谢。我添加了空格，然后就得到表格了，很感谢！

**Comment by Z4HD** [comment]
@QingyangChen 既然问题得到了完美的解决那么为何不`close issue`呢？
