### ISSUE TITLE
主页背景图滚动速度

### ISSUE THREAD

**Issue by lhy0609** [iTimeTraveler/hexo-theme-hiero#30]
您的主题很漂亮！我也clone了一个

问一下主页背景图滚动速度的快慢可以设置吗？

**Comment by iTimeTraveler** [comment]
@lhy0609 Hello，你说的[hexo-theme-hiker](https://github.com/iTimeTraveler/hexo-theme-hiker)这个主题吧，而不是我们现在所在的这个工程。如果是hiker这个主题的话，首页背景图滚动速度在 `hexo-theme-hiker/layout/_partial/header.ejs` 文件夹下的[第53行](https://github.com/iTimeTraveler/hexo-theme-hiker/blob/master/layout/_partial/header.ejs#L53)

```
$('section.awSlider .carousel').carousel({
              pause: '',
              interval: 5000
          });
```

其中这个`interval: 5000` 代表间隔5秒轮换下张图，你可以改改试试。

**Comment by lhy0609** [comment]
对是hiker主题，不好意思看错了。
我试了你说的方法，是可行的。谢谢！

**Comment by Z4HD** [comment]
@lhy0609 如果您的问题得到了妥善解决，请及时close issue，3Q2X
