### ISSUE TITLE
首页文章的缩略图

### ISSUE THREAD

**Issue by Git-shawnhu** [iTimeTraveler/hexo-theme-hiero#34]
您好，请问一下，怎么为文章在“首页”和“最近更新”的地方，添加（像您的网站 https://itimetraveler.github.io/hexo-theme-hiero/ 展示的）那样的缩略图呢？谢谢！

**Comment by iTimeTraveler** [comment]
@Git-shawnhu Hello， 我的这个Demo站点的源文件在这里，你可以参考下：https://github.com/iTimeTraveler/hexo-theme-hiero/tree/site-source

**Comment by Git-shawnhu** [comment]
谢谢您的回复 @iTimeTraveler  仔细看了一下，因为也是第一次弄，不是很清楚目标在哪里，您能跟我说一下应该在哪个文件夹或者文件去调整么？感谢！

**Comment by Git-shawnhu** [comment]
@iTimeTraveler  谢谢您的回复！研究了几个小时，还是没有找到要领，不知道修改编辑的目标文件或代码应该在哪个部分。能指点一下么？感谢！就是希望首页打开能像您的demo网站那样有缩略图，然后read more，不用文章全部铺开。谢谢 ：）

**Comment by Git-shawnhu** [comment]
@iTimeTraveler 您好！我自己已经解决了这个问题了。原来是需要添加**代码。Thanks anyway! 

一个新出现的问题是，打开每一个page，现在页面顶端都会出现图片，不知道从哪里可以关闭这个自动顶端的大图？谢谢！

**Comment by iTimeTraveler** [comment]
@Git-shawnhu 你试着把主题中`_config.yml`配置文件里的`about_big_image`字段清空改成下面这个样子，看看是否大图还在：

```yml
# AboutPage background
about_big_image: []
```

我怀疑你说的这个大图是本来希望它只在关于页面显示，可能是我写的过滤代码有问题，所以在每个页面都有了

**Comment by Z4HD** [comment]
@iTimeTraveler 
我在`header-post.ejs`中添加下列代码：

``` ejs
<%= page.link %> <br />
<%= page.source %> <br />
<%= page.layout %> <br />
<%= page.path %> <br />
<%= page.path=='about/index.html' %> <br />
```

使用`hexo server`查看时能够正常返回值（示例为about界面）

```
undefined 
about/index.md 
about 
about/index.html 
true 
```

使用`hexo g`生成静态文件后则任何页面都会返回下列值：

```
undefined <br />
404.html <br />
page <br />
404.html <br />
false <br />
```

我也很无奈啊
