### ISSUE TITLE
请问如何添加百度统计？

### ISSUE THREAD

**Issue by HelloSilicat** [iTimeTraveler/hexo-theme-hiero#45]
在config中的baidu_analytics应该如何设置？  谢谢~

**Comment by zehuichen123** [comment]
give the baidu id directly
<img width="1245" alt="1" src="https://user-images.githubusercontent.com/24351120/35794964-a3552a10-0a92-11e8-80e8-d4d37fdd16d2.png">
<img width="991" alt="2" src="https://user-images.githubusercontent.com/24351120/35795046-d9aa3448-0a92-11e8-8ac8-85d57a61bead.png">
