### ISSUE TITLE
提几个建议

### ISSUE THREAD

**Issue by xiaomubiao** [iTimeTraveler/hexo-theme-hiero#5]
首先布局我很喜欢，但是我不太明白你的 模板定位，如果是新闻模板在 文章页面居然还有目录，貌似目录这个东西看着不习惯，可能我不是程序员，大致说点个人观点吧
一 、字体不太好，我觉得常规设置就好 参照这个https://nervouself.github.io/ 我用他的模板做了个博客，电脑手机看着觉得字体都可以，看了源文件就是常规设定
二、如果保持目前的列宽，我觉得分类目录起码一行 两个，然后就是标签，一行起码 三到四个，归档也是 一行放两个更好
三、标签云不够醒目，目前的颜色设定不够突出
四、配色大黑head 感觉 太严肃了，，，小清新配色感觉更流行
大致就这么多，顺便问一下你做模板是为了练手还是为了 实用？

**Comment by iTimeTraveler** [comment]
@xiaomubiao 恩，首先多谢你的建议。

这个主题其实是源自Wordpress主题 [Hiero for Wordpress]( https://athemes.com/theme/hiero/)  基本沿袭了它的视觉风格，包括字体（中文我选的不太好）

> 1、字体方面

特别是中文字体因为原生主题中没有，为了搭配黑红的主题配色，前前后后试了几种字体都觉得有些不搭。不过如果可以的话你试着改改，然后直接给我提个Pull Request最好了，字体我慢慢优化

> 2、文章目录

这个其实本意是为了大家读长文章的时候阅读方便，可以考虑设置一个显示与否的选项。好改

> 3、标签云

这个小组件如果改成和最新文章这个组件差不多的样式你觉得会好些么

> 4、整体配色

唉，说到这个，我就不太擅长了，其实这几个主题的本意是想给自己写个专门的好看的主题用，因为Hexo的主题可选的不多，有几个好看的用久了也有些腻所以想换个就写了这几个。其中，[Hiker](https://github.com/iTimeTraveler/hexo-theme-hiker)主题是一个个人的项目想法当时没实现完，然后移植成了一个主题，另外两个（Hiero和[Hipaper](https://github.com/iTimeTraveler/hexo-theme-hipaper)）是Wordpress主题移植过来的，也是想用这种半报纸风格的主题就写了个自己用，大概就是这样。配色方面我觉得你也可以改改然后直接给我提个Pull Request，改起来其实也不难

**Comment by xiaomubiao** [comment]
谢谢回复，我混 github 就是为了找几个 hexo 主题，坦白地说大部分都是程序员自用的，也无所谓好看不好看，但是我不会用 git 也不懂代码 只是随便改改主题，国内 WP 主题以 大前端最为经典，我喜欢你这个主题也是因为和大前端的布局比较相似，http://www.daqianduan.com/,他是商业主题，所以配色和细节做的好一点，你可以参考下，还有一个仿他的hexo 主题http://jelon.top/，字体是自带的，我觉得还不错，配色小清新
其实对于主题而言我是比较困惑的，我基本上都是用笔记本14寸，我不太确定，当我进入网站首页，我会接收到多少信息，多少是我感兴趣的，所以 简洁、大方、条理分明，大气、重点突出，会让网站更有格调，其实很多网站用商业主题可能都是为了让自己看起来更高端 正规。
所以 定位很重要，所以感觉你的主题首页和文章页就有点不匹配，也就是说主题是为程序员设计的还是能撑起一个盈利的商业化的网站，这就需要定位了。
所以我觉得你可以考虑下移植大前端的主题，当然他的主题功能太多，有点繁琐，完全可以精简精简，我相信那样受众人群会更多，红黑配色我觉得有点沉重，大概就想到这么多

**Comment by iTimeTraveler** [comment]
@xiaomubiao 哈哈哈，好的。多谢你的推荐，说实话推荐的我还真不知道，确实挺好看的。明年有空了我试着移植一下，顺便祝你新年快乐啊

**Comment by xiaomubiao** [comment]
也祝你新年快乐，等你好消息，明年准备批量做几个站。

**Comment by Z4HD** [comment]
觉得字体辣眼睛的看来不止我一个（笑）
----
然而我简单粗暴的查找+替换，把字体都换成微软雅黑了...

>（我当初选择这个款主题的原因是因为它看起来很严肃、很低调，而且黑色给人一种典雅不做作的感觉。）

**Comment by iTimeTraveler** [comment]
@Z4HD 中文确实不好看，那我把它们都换成雅黑算了

**Comment by Z4HD** [comment]
@iTimeTraveler 对，这个还是由您来做比较妥当，我这种乱改法容易污染仓库。

话说您做几个大的改进之后打个标签吧，方便大家集体更新主题文件。

**Comment by iTimeTraveler** [comment]
@Z4HD hello，除了文章内目录我保留了那个比较有特点的字体之外。其他的中文字体我大概都换了，包括首页文章标题、文章内标题都换成了雅黑。你看看现在Demo页面会不会好些。还有我的个人博客也更新了

**Comment by Z4HD** [comment]
@iTimeTraveler 字体更改的非常好，可是为何不close这个issue呢？
