### ISSUE TITLE
关于代码块的style

### ISSUE THREAD

**Issue by medmin** [iTimeTraveler/hexo-theme-hiero#50]
这下子确实似乎是个问题：

我刚才把blockquote的styl文件改了一下，就是`themes/hiero/source/css/_partial/article.styl`
然后hexo generate，最终的style.css没有任何变化
然后我把整个`/public/css`目录全删了，再重新hexo generate，就好了。
这就是目前的情况。

也就是说，如果改动了.styl文件，似乎要把`/public/css`目录全删了， 再重新hexo generate。

不知道这是hexo的问题，还是咱这个theme的问题？

=========原来的issue===========

您好，我修改了`themes/hiero/source/css/_partial/highlight.styl`

用hexo server可以看得出代码块的style变了
但hexo generate之后，仍然是老的style

老的style：
![old](https://user-images.githubusercontent.com/16820635/37310714-0a4ee7f8-2602-11e8-9bc9-52abcd681a18.png)

新的style:
![new](https://user-images.githubusercontent.com/16820635/37310732-17b24818-2602-11e8-84b1-6f41c7eda560.png)

请问这个问题是出在什么地方？

难道其他地方的style override了这个`highlight.styl`里的代码？

**Comment by medmin** [comment]
chrome缓存的原因！！
不好意思，打搅了。

**Comment by iTimeTraveler** [comment]
@medmin 好的
