### ISSUE TITLE
关于resent post问题

### ISSUE THREAD

**Issue by wanxiaoyy** [iTimeTraveler/hexo-theme-hiero#61]
除了首页的resent post显示有图片，其他页面的resent post 均不显示图片？？？？？

**Comment by Juvenal-Yescas** [comment]
This happens when the images are also hosted on the same server, but if they are hosted on another server, (Example: [imgbb.com](https://www.imgbb.com "Upload and share your images")) does not happen, because the image route is direct from any article.

We will correct this detail soon. @wanxiaoyy
