### ISSUE TITLE
Display hierarchical structure in categories page

### ISSUE THREAD

**Issue by chao1995** [iTimeTraveler/hexo-theme-hiero#7]
Greetings! Thanks for making the theme, I really like it and start using it in my blog.

One problem I faced is that currently the category page is not able to display the hierarchy because it simply loops over `site.categories`.

In Hexo, the categories are designed to be hierarchical while tags are not ([here is Hexo docs](https://hexo.io/docs/front-matter.html#Categories-amp-Tags)).

So I wrote a simple helper adapted from hexo's [list_category](https://hexo.io/docs/helpers.html#list-categories) helper, and also keep the style of `categories.ejs` from your theme. It's already used in my blog's [category page](https://chao1995.github.io/blog/categories/) so you can see what the result is like.

The change is, suppose we only have one post, and it belongs to `category A` then `subcategory B` then `subcategory C`, it then will only be displayed in `category A > subcategory B > subcategory C`. Note `category A` and `subcategory B` will not be shown at all because there are no posts directly under them.

If you think this feature is worth supporting, I am happy to submit a PR for it. :)

Cheers!

**Comment by iTimeTraveler** [comment]
@chao1995  Yeah, sure. wonderful function for me and I believe it's worth to support for this project.

So just submit your PR and I'll appreciate that. thank you @chao1995 :+1:

**Comment by chao1995** [comment]
@iTimeTraveler Thanks for your reply! I will submit the PR in the next couple of days. :)
