### ISSUE TITLE
网页加载速度非常卡

### ISSUE THREAD

**Issue by baylin87** [iTimeTraveler/hexo-theme-hiero#9]
看上去是因为要加载网上google字体，每次本地测试加载都特别慢，偶尔还崩溃，能不能修复。。

**Comment by iTimeTraveler** [comment]
应该和Google字体关系不大吧，用的这个Google字体在国内的CDN还挺多的。实际测试结果都还可以，你看看这个：

[fonts.googleapis.com访问速度测试](http://ping.chinaz.com/fonts.googleapis.com/css)

**Comment by Z4HD** [comment]
私以为还是字体本地化或者使用装机量排前几的字体比较妥当。

**Comment by iTimeTraveler** [comment]
@Z4HD 确实是，静态网站外链资源越少越好。

**Comment by Z4HD** [comment]
没人关这个issue？

**Comment by GWesley** [comment]
我倒是遇到了safari打开困难的情况，看了下是某个js请求超时了， 具体卡在哪里在控制台看一下就行了
